name: Build source and wheel packages

on: push

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-11, macos-12, ubuntu-20.04, ubuntu-22.04 ]
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v3

      - name: Workaround github issue https://github.com/actions/runner-images/issues/7192
        if: startsWith(matrix.os, 'ubuntu-')
        run: sudo echo RESET grub-efi/install_devices | sudo debconf-communicate grub-pc

      - name: Install required system packages for macOS
        if: startsWith(matrix.os, 'macos-')
        run: |
          brew update
          brew tap cuber/homebrew-libsecp256k1
          brew install libsecp256k1

      - name: Install required system packages only for Ubuntu Linux
        if: startsWith(matrix.os, 'ubuntu-')
        run: |
          sudo apt-get update
          sudo apt-get -y upgrade
          sudo apt-get install -y libsecp256k1-dev

      - name: Install required Python packages
        run: |
          python3 -m pip install --upgrade build
          python3 -m pip install --user --upgrade twine

      - name: Build source and wheel packages
        run: |
          python3 -m build

      - name: Install the Python wheel
        run: |
          python3 -m pip install dist/aleph_sdk_python-*.whl

      - name: Import and use the package
        # macos tests fail this step because they use Python 3.11, which is not yet supported by our dependencies
        if: startsWith(matrix.os, 'ubuntu-')
        run: |
          python3 -c "import aleph.sdk"
          python3 -c "from aleph.sdk.chains.ethereum import get_fallback_account; get_fallback_account()"
