name: Build source and wheel packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12, macos-13, macos-14, ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Workaround github issue https://github.com/actions/runner-images/issues/7192
        if: startsWith(matrix.os, 'ubuntu-')
        run: sudo echo RESET grub-efi/install_devices | sudo debconf-communicate grub-pc

      - name: Set up Python
        if: startsWith(matrix.os, 'macos')
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-build-wheels-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-build-wheels-

      - name: Install required system packages for macOS
        if: startsWith(matrix.os, 'macos-')
        run: |
          brew update
          brew tap cuber/homebrew-libsecp256k1
          brew install libsecp256k1

      - name: Install required system packages only for Ubuntu Linux
        if: startsWith(matrix.os, 'ubuntu-')
        run: |
          sudo apt-get update
          sudo apt-get -y upgrade
          sudo apt-get install -y libsecp256k1-dev

      - name: Install Hatch
        run: |
          python3 -m venv /tmp/venv
          /tmp/venv/bin/python3 -m pip install --upgrade hatch

      - name: Build source and wheel packages
        run: |
          /tmp/venv/bin/python3 -m hatch build

      - name: Install the Python wheel
        run: |
          /tmp/venv/bin/python3 -m pip install dist/aleph_sdk_python-*.whl

      - name: Install `setuptools` on systems where it is missing by default
        run: /tmp/venv/bin/python3 -m pip install --upgrade setuptools
        if: matrix.os == 'ubuntu-24.04'

      - name: Import and use the package
        run: |
          /tmp/venv/bin/python3 -c "import aleph.sdk"
          /tmp/venv/bin/python3 -c "from aleph.sdk.chains.ethereum import get_fallback_account; get_fallback_account()"
